apiVersion: 1

datasources:
  - name: Monitoring Postgres
    uid: monitoring-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: monitor
    jsonData:
      database: monitoring
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: monitor
    isDefault: true
    editable: true
